accounts:
  - name: user1
    coins: ["500drop", "10000token", "100000000stake"]
  - name: user2
    coins: ["500drop", "10000token", "100000000stake"]
  - name: dropgiverfaucet
    coins: ["100000000drop", "1000token"]
validator:
  name: user1
  staked: "100000000stake"
